copyright = "© 2025 Kseniia Shevchenko Photography. All rights reserved"
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "America/Chicago"
timeout = "120s"
title = "Photography by Kseniia Shevchenko"

[params]
  defaultTheme = "dark"
  description = "Capturing harmony through every frame."
  title = "Photography by Kseniia Shevchenko"
  [params.author]
    email = "life.balance24h@gmail.com"
    name = "Kseniia Shevchenko Photography"
  [params.socialIcons]
    facebook = "https://www.facebook.com/profile.php?id=100017218727350"
    instagram = "https://www.instagram.com/life.balance24h/"
    #github = "https://github.com/tiksn/LifeBalanceWebsite/"
    #youtube = "https://www.youtube.com/"
    email = "mailto:life.balance24h@gmail.com"
    #website = "https://example.com"
    #mastodon = "https://example.com"
    #pixelfed = "https://example.com"
    #mixcloud = "https://example.com"
    #flickr = "https://www.flickr.com"
    #500px = "https://500px"
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[menu]
  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/tiksn/LifeBalanceWebsite/"
    weight = 3

[services]
  [services.rss]
    limit = 100
